apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.appSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: strapi
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-jwt-secret: {{ .Values.application.admin_jwt_secret | b64enc | quote }}
  api-token-salt: {{ .Values.application.jwt_secret | b64enc | quote }}
  app-keys: {{ join "," .Values.application.app_keys | b64enc | quote }}
  jwt-secret: {{ .Values.application.jwt_secret | b64enc | quote }}
